### ISSUE TITLE
Vacation calendar based on event type instead of keyword

### ISSUE THREAD

**Issue by danielmarbach** [gsuitedevs/solutions#95]
I was looking into the vacation calendar. Pretty neat! I was wondering why the vacation calendar uses [keywords ](https://github.com/gsuitedevs/solutions/blob/master/vacation-calendar/src/Code.js#L8)instead of event types? Calendar already has an "out of office" type that could be used automatically.

**Comment by erickoledadevrel** [comment]
Unfortunately there isn't a stable way to determine if an event is of the special out-of-office type in the Calendar API. Once that becomes available I'd add support for it in addition to keywords, but I think it would be good if the script also used keywords, since I don't think everyone uses those new types of events.

**Comment by simaoafonso-pwt** [comment]
See #209
